import type { Language } from '../types';

export const MEGA_INGREDIENTS: Record<Language, string[]> = {
  ru: [
    'Авокадо',
    'Абрикос',
    'Аджика',
    'Айсберг',
    'Анис',
    'Анчоусы',
    'Апельсин',
    'Арахис',
    'Арбуз',
    'Артишок',
    'Баклажан',
    'Базилик',
    'Бальзамический уксус',
    'Бамия',
    'Банан',
    'Баранина',
    'Барбарис',
    'Батат',
    'Бекон',
    'Белое вино',
    'Белые грибы',
    'Брокколи',
    'Брусника',
    'Булгур',
    'Буженина',
    'Ваниль',
    'Васаби',
    'Ветчина',
    'Виноград',
    'Вишня',
    'Вода',
    'Водоросли нори',
    'Вустерширский соус',
    'Гарам масала',
    'Гвоздика',
    'Герань',
    'Говядина',
    'Голубика',
    'Горох',
    'Горчица',
    'Горчичный порошок',
    'Гранатовый соус',
    'Грейпфрут',
    'Гречка',
    'Грибы',
    'Грудинка',
    'Груша',
    'Дайкон',
    'Дрожжи',
    'Дыня',
    'Ежевика',
    'Зеленый горошек',
    'Зеленый лук',
    'Зеленый чай',
    'Зелень',
    'Зира',
    'Изиум',
    'Имбирь',
    'Индейка',
    'Инжир',
    'Йогурт',
    'Кабачок',
    'Какао',
    'Кальмары',
    'Камбала',
    'Каперсы',
    'Капуста',
    'Кардамон',
    'Карри',
    'Картофель',
    'Квас',
    'Кедровые орехи',
    'Кешью',
    'Кетчуп',
    'Кинза',
    'Киноа',
    'Киви',
    'Кленовый сироп',
    'Клубника',
    'Клюква',
    'Кокосовое молоко',
    'Кокосовая стружка',
    'Колбаса',
    'Кориандр',
    'Корица',
    'Корнишоны',
    'Кофе',
    'Краб',
    'Крахмал',
    'Креветки',
    'Кролик',
    'Крупа манная',
    'Кукуруза',
    'Кумин',
    'Кунжут',
    'Кунжутное масло',
    'Курага',
    'Курица',
    'Куркума',
    'Кускус',
    'Лавровый лист',
    'Лайм',
    'Лемонграсс',
    'Лимон',
    'Лисички',
    'Лосось',
    'Лук белый',
    'Лук красный',
    'Лук порей',
    'Лук репчатый',
    'Лук шалот',
    'Майоран',
    'Майонез',
    'Макароны',
    'Малина',
    'Манго',
    'Мандарин',
    'Маргарин',
    'Маринад',
    'Маслины',
    'Масло оливковое',
    'Масло подсолнечное',
    'Масло сливочное',
    'Масло топленое',
    'Мед',
    'Мидии',
    'Миндаль',
    'Минтай',
    'Мисо паста',
    'Молоко',
    'Молоко сгущенное',
    'Морковь',
    'Морская капуста',
    'Морская соль',
    'Мука пшеничная',
    'Мука ржаная',
    'Мускатный орех',
    'Мята',
    'Наршараб',
    'Нут',
    'Облепиха',
    'Овсяные хлопья',
    'Огурец',
    'Окунь',
    'Оливки',
    'Оливковое масло',
    'Орегано',
    'Орехи',
    'Осетрина',
    'Отруби',
    'Палтус',
    'Паприка',
    'Пармезан',
    'Пастернак',
    'Паста',
    'Патиссон',
    'Пекинская капуста',
    'Перепелиные яйца',
    'Перец болгарский',
    'Перец душистый',
    'Перец красный (чили)',
    'Перец черный ко горошком',
    'Перловка',
    'Персик',
    'Петрушка',
    'Печень говяжья',
    'Печень куриная',
    'Печень трески',
    'Пиво',
    'Помидор',
    'Помидоры черри',
    'Проростки пшеницы',
    'Простокваша',
    'Пшено',
    'Раки',
    'Рапсовое масло',
    'Ревень',
    'Редис',
    'Редька',
    'Репа',
    'Рис белый',
    'Рис бурый',
    'Рис дикий',
    'Розмарин',
    'Ром',
    'Рукола',
    'Рыба',
    'Рябина',
    'Ряженка',
    'Салат латук',
    'Сало',
    'Сахар',
    'Сахарная пудра',
    'Свекла',
    'Свинина',
    'Сгущенка',
    'Сельдерей',
    'Сельдь',
    'Семечки подсолнуха',
    'Семга',
    'Сироп',
    'Скумбрия',
    'Слива',
    'Сливки',
    'Сливочное масло',
    'Сметана',
    'Сода',
    'Соевое молоко',
    'Соевый соус',
    'Соль',
    'Солодка',
    'Сом',
    'Соус табаско',
    'Соус тартар',
    'Соус томатный',
    'Спаржа',
    'Сыр гауда',
    'Сыр моцарелла',
    'Сыр рикотта',
    'Сыр фета',
    'Сыр чеддер',
    'Тархун',
    'Творог',
    'Телятина',
    'Тимьян',
    'Тмин',
    'Томатная паста',
    'Топинамбур',
    'Треска',
    'Трюфельное масло',
    'Тунец',
    'Тыква',
    'Тыквенные семечки',
    'Уксус',
    'Укроп',
    'Устрицы',
    'Утка',
    'Фасоль белая',
    'Фасоль красная',
    'Фасоль стручковая',
    'Фенхель',
    'Финики',
    'Фисташки',
    'Форель',
    'Фундук',
    'Халва',
    'Хамон',
    'Хлеб пшеничный',
    'Хлеб ржаной',
    'Хлопья кукурузные',
    'Хмель-сунели',
    'Хрен',
    'Хурма',
    'Цветная капуста',
    'Цедра лимона',
    'Цукини',
    'Цыпленок',
    'Чай черный',
    'Чеддер',
    'Черемуха',
    'Черешня',
    'Черная смородина',
    'Черника',
    'Чернослив',
    'Черный перец',
    'Чеснок',
    'Чечевица',
    'Чиа семена',
    'Шампиньоны',
    'Шалфей',
    'Шафран',
    'Шиповник',
    'Шпинат',
    'Шпроты',
    'Щука',
    'Эстрагон',
    'Яблоки',
    'Ягнятина',
    'Ягода',
    'Яйцо куриное',
    'Яйцо перепелиное',
    'Ячмень',
  ],
  en: [
    'Apple',
    'Apricot',
    'Artichoke',
    'Arugula',
    'Asparagus',
    'Avocado',
    'Almonds',
    'Anchovies',
    'Anise',
    'Bacon',
    'Balsamic vinegar',
    'Banana',
    'Barley',
    'Basil',
    'Bay leaf',
    'Beans',
    'Beef',
    'Beer',
    'Beetroot',
    'Bell pepper',
    'Black pepper',
    'Blackberries',
    'Blueberries',
    'Bread',
    'Broccoli',
    'Brown rice',
    'Brussels sprouts',
    'Buckwheat',
    'Butter',
    'Cabbage',
    'Cantaloupe',
    'Capers',
    'Caraway',
    'Cardamom',
    'Carrot',
    'Cashews',
    'Cauliflower',
    'Celery',
    'Cheddar',
    'Cheese',
    'Cherry',
    'Chia seeds',
    'Chicken',
    'Chickpeas',
    'Chili pepper',
    'Chives',
    'Chocolate',
    'Cilantro',
    'Cinnamon',
    'Clams',
    'Cloves',
    'Coconut milk',
    'Cod',
    'Coffee',
    'Coriander',
    'Corn',
    'Couscous',
    'Crab',
    'Cranberries',
    'Cream',
    'Cucumber',
    'Cumin',
    'Currants',
    'Curry',
    'Dates',
    'Dill',
    'Duck',
    'Eggplant',
    'Eggs',
    'Endive',
    'Fennel',
    'Fenugreek',
    'Feta',
    'Figs',
    'Fish',
    'Flax seeds',
    'Flour',
    'Garlic',
    'Ginger',
    'Goat cheese',
    'Goose',
    'Grapes',
    'Green beans',
    'Green tea',
    'Ground beef',
    'Guava',
    'Halibut',
    'Ham',
    'Hazelnuts',
    'Honey',
    'Horseradish',
    'Hummus',
    'Iceberg lettuce',
    'Icing sugar',
    'Jalapeno',
    'Jasmine rice',
    'Kale',
    'Ketchup',
    'Kidney beans',
    'Kiwi',
    'Kohlrabi',
    'Lamb',
    'Lard',
    'Lavender',
    'Leek',
    'Lemon',
    'Lemongrass',
    'Lentils',
    'Lettuce',
    'Lime',
    'Lobster',
    'Lotus root',
    'Macadamia nuts',
    'Mackerel',
    'Mango',
    'Maple syrup',
    'Marjoram',
    'Marshmallows',
    'Mayonnaise',
    'Milk',
    'Mint',
    'Miso paste',
    'Molasses',
    'Mozzarella',
    'Mushrooms',
    'Mussels',
    'Mustard',
    'Mutton',
    'Nectarine',
    'Nori',
    'Nutmeg',
    'Oatmeal',
    'Oats',
    'Olive oil',
    'Olives',
    'Onion',
    'Orange',
    'Oregano',
    'Oysters',
    'Paprika',
    'Parmesan',
    'Parsley',
    'Parsnip',
    'Pasta',
    'Peach',
    'Peanuts',
    'Pear',
    'Peas',
    'Pecans',
    'Pesto',
    'Pickles',
    'Pine nuts',
    'Pineapple',
    'Pistachios',
    'Plum',
    'Pomegranate',
    'Pork',
    'Potato',
    'Prawns',
    'Pumpkin',
    'Quail eggs',
    'Quince',
    'Quinoa',
    'Radish',
    'Raisins',
    'Raspberries',
    'Red cabbage',
    'Red onion',
    'Red wine',
    'Rhubarb',
    'Ribs',
    'Rice',
    'Ricotta',
    'Roast beef',
    'Rosemary',
    'Rum',
    'Saffron',
    'Sage',
    'Salmon',
    'Salt',
    'Sardines',
    'Sausage',
    'Scallops',
    'Sea salt',
    'Seaweed',
    'Sesame oil',
    'Sesame seeds',
    'Shallot',
    'Shrimp',
    'Smoked salmon',
    'Snow peas',
    'Sour cream',
    'Soy milk',
    'Soy sauce',
    'Soybeans',
    'Spinach',
    'Squash',
    'Squid',
    'Star anise',
    'Steak',
    'Strawberries',
    'Sugar',
    'Sunflower oil',
    'Sunflower seeds',
    'Sweet potato',
    'Swiss cheese',
    'Tabasco',
    'Tahini',
    'Tamarind',
    'Tarragon',
    'Tea',
    'Thyme',
    'Tofu',
    'Tomato',
    'Tomato paste',
    'Trout',
    'Truffle oil',
    'Tuna',
    'Turkey',
    'Turmeric',
    'Turnip',
    'Vanilla',
    'Veal',
    'Venison',
    'Vinegar',
    'Walnuts',
    'Wasabi',
    'Water',
    'Watercress',
    'Watermelon',
    'Wheat',
    'White rice',
    'White wine',
    'Worcestershire sauce',
    'Yeast',
    'Yellow onion',
    'Yogurt',
    'Zucchini',
  ],
};
